### ISSUE TITLE
Add fields for used packs/agents/runners

### ISSUE THREAD

**Issue by fredg02** [EclipseFdn/cbi-sponsorships-api#23]
To avoid having to compute the number of used packs/agents/runners on the client side, the following fields should be added to `memberOrganizationsBenefits`:

* resourcePacks_used
* dedicatedAgents_used
* ghLargeRunners_used

The numbers will be calculated and synchronized before deployment.

**Comment by chrisguindon** [comment]
Closing this issue. We took a closer look at the source code for this project and we won't think this is something we can do with this API.

I think my team can manage this by exposing this data via our existing API.

TLDR; We will fetch a copy of https://api.eclipse.org/cbi/sponsorships/ once a day and expose the data via our membership and project API.

**Comment by autumnfound** [comment]
This is something that is needed and shouldn't have been closed, as this aligns well with the single endpoint model still and is data I'm not sure where it exists. There would still be value of having this endpoint be the single source of truth, while having the downstream consumers filter the data for easier access as needed.

**Comment by chrisguindon** [comment]
Thanks @autumnfound - I accidently closed the wrong issue!
